spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

oauth:
  redirect-uris:
    kakao:
      - http://localhost:3000/oauth/kakao/callback
      - ${KAKAO_REDIRECT_URI}
    google:
      - http://localhost:3000/oauth/google/callback
      - ${GOOGLE_REDIRECT_URI}
