spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true

kakao:
  redirect-uri: http://localhost:3000/oauth/kakao/callback

google:
  redirect-uri: http://localhost:3000/oauth/google/callback