spring:
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true

oauth:
  redirect-uris:
    kakao:
      - http://localhost:3000/oauth/kakao/callback
    google:
      - http://localhost:3000/oauth/google/callback
